[package]
name = "life"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

[dependencies]
term = { path = "../term" }
util = { path = "../util" }
log = "*"
pretty_env_logger = "*"
rand = "*"
piston_window = "*"