[package]
name = "main"
version = "0.0.0"
authors = ["First Last <firstlast@firstlast.kom>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
rand = "0.7.3"