[package]
name = "asteroids"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

[workspace]
members = [ "adventofcode", "main", "life" ,"ipc", "util", "term" ]

[dependencies]
main = { path = "main" }
adventofcode = { path = "adventofcode" }
life = { path = "life" }