[package]
name = "asteroids"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

[workspace]
members = [ "main", "life" ,"ipc", "util", "term" ]

[dependencies]
#main = { path = "main" }
life = { path = "life" }