[package]
name = "main"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc = { path = "../ipc" }
util = { path = "../util" }
libc = "0.2"
log = "0.4.11"
env = "0.0.0"
pretty_env_logger = "0.4.0"
rand = "0.7.3"
json = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57" 
piston_window = "0.113.0"
vecmath = "1.0.0"